### ISSUE TITLE
GNU C Library’s (glibc) iconv function (CVE-2024-2961)

### ISSUE THREAD

**Issue by hdell** [winlibs/glib#2]
Are you aware of this CVE issue? 

Does the iconv library implemented with Win32 API have the same issue as the current glibc documented in CVE-2024-2961?

**Comment by ndossche** [comment]
Although this is the wrong repo (this is glib, not glib**c**), I've raised this issue internally for the libiconv library.

**Comment by hdell** [comment]
Thanks for the update and interest in this issue... Again, thanks for the quick response. I know there are some differences, however, I see a file glib-2.dll is part of PHP distro that I use for Windows with IIS Web Server. It seems to match the version listed here. Is this source code here used for glib-2.dll?

I am a noob on these lower-level kinds of things; however, I thought it would be a good question to ask to see what commonality exists between glib and glibc. I am more of a generalist and more focused on system admin on Windows.

Part of this CVE is related to newer characters sets. ISO-2022-CN is mentioned. As far as I can see it looks like the ISO-2022-CN character set is **NOT** implement here. I don't write in C and can't fully read C either to see if the buffer overflow issue is present in this library regardless of character set implementation. Also, I believe ISO-2022-CN was added to Windows as a patch after 2022 Edition was released.

It would be good to get the word out that PHP on Windows is "safe" from this exploit. Maybe update the CVE?

**Comment by ndossche** [comment]
The libiconv we ship with the PHP Windows builds has been updated, although it seems that was never vulnerable in the first place since it's different from glibc's iconv.

> I know there are some differences, however, I see a file glib-2.dll is part of PHP distro that I use for Windows with IIS Web Server. It seems to match the version listed here. Is this source code here used for glib-2.dll?
> I am a noob on these lower-level kinds of things; however, I thought it would be a good question to ask to see what commonality exists between glib and glibc. I am more of a generalist and more focused on system admin on Windows.

This is not glibc, this is glib, those are two completely different libraries. It's just unfortunate that the names are so similar.

> It would be good to get the word out that PHP on Windows is "safe" from this exploit.

It's safe.

> Maybe update the CVE?

This is not our CVE, it's glibc's CVE, and therefore we don't have access to it.
There's a lot of misinformation about the vulnerability online, but the gist is that it's a bug in glibc, not PHP, that was fixed at glibc's side. The mentions of PHP is just to hype up the vulnerability.
